export enum InfrastructureMapMode {
  SHAPE = 'SHAPE',
  RESTRICTED_SHAPE = 'RESTRICTED_SHAPE',
  RECTANGLE = 'RECTANGLE',
  RESTRICTED_RECTANGLE = 'RESTRICTED_RECTANGLE',
  WORK_STATION = 'WORK_STATION',
  CHARGING_STATION_DOCK = 'CHARGING_STATION_DOCK',
  CHARGING_STATION_TRACK = 'CHARGING_STATION_TRACK',
  CHARGING_STATION = 'CHARGING_STATION',
  WAYPOINT = 'WAYPOINT',
  CAMERA = 'CAMERA',
  ANCHOR = 'ANCHOR',
}
