export enum ShapeType {
  AREA = 'AREA',
  STATION = 'STATION',
  WORK = 'WORK',
  WAYPOINT = 'WAYPOINT',
  CHARGING = 'CHARGING',
  CHARGING_DOCK = 'CHARGING_DOCK',
  CHARGING_TRACK = 'CHARGING_TRACK',
  DEVICE = 'DEVICE',
  ANCHOR = 'ANCHOR',
  CAMERA = 'CAMERA',
}
